# Distance from the edge at which the camera will pan
pan_edge_offset = 80
# How many pixels per second the camera will pan
pan_speed = 15

# Interval in seconds for when a unit spawns
unit_spawn_interval = 10
enemy_unit_spawn_interval = 12

# Downward force on all projectiles
projectile_gravity = 2.5

# Physics engine specific settings
[physics]
# How many substeps are taken in a single step
substeps = 20
# Gravity applied to everything
gravity = 9.81
# Damping applied to the velocity every timestep
air_friction = 0.95
