allegiance = "player"

# Sprites to render
base_asset_path = "unit.base-1"
hands_asset_path = "unit.spear-hands-1"
projectile_asset_path = "projectile.spear-1"

# How many pixels a unit moves in a second
walk_speed = 15

# Interval in seconds for when a new projectile is thrown
projectile_spawn_interval = 5
# How fast a projectile is thrown
projectile_velocity = { min = 40, max = 50 }
# How long the hands are hidden after launching a projectile in seconds
hide_hands_delay = 9
